/**
 * Bundles styles/*.css and js/*.js into the inline <style> and <script> blocks
 * of index.html.
 *
 * index.html ships as one self-contained file — it has no <link rel=stylesheet>
 * and no <script src> — so the browser only ever runs the inlined copies.
 * Before this script existed those copies were maintained by hand, which meant
 * an edit to js/ or styles/ could look correct in the repo and change nothing
 * in the deployed studio.
 *
 * styles/ and js/ are the source. Run `npm run bundle` after editing either.
 *
 *   node build.js          rewrite index.html from source
 *   node build.js --check  verify index.html is in sync (non-zero exit if not)
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const CSS_ORDER = [
  'styles/main.css',
  'styles/navbar.css',
  'styles/hero.css',
  'styles/film-os.css',
  'styles/studio.css',
  'styles/storyboard.css',
  'styles/compositor.css',
  'styles/director.css',
  'styles/presets.css',
  'styles/community.css',
  'styles/pricing.css'
];

// Explicit, because load order is load-bearing: film-os defines the state
// store the studio and UI controllers read at startup, and app.js boots last.
const JS_ORDER = [
  'js/supabase.js',
  'js/post-fx.js',
  'js/video-engine.js',
  'js/film-os.js',
  'js/audio-engine.js',
  'js/neural-engine.js',
  'js/showcase.js',
  'js/studio.js',
  'js/film-ui.js',
  'js/presets.js',
  'js/projects.js',
  'js/pricing.js',
  'js/app.js'
];

// js/human-assets.js is a multi-megabyte base64 blob that nothing references;
// it is deliberately not bundled.

const INDEX = path.join(__dirname, 'index.html');

function buildBundle(order, guard) {
  return order.map(rel => {
    const abs = path.join(__dirname, rel);
    if (!fs.existsSync(abs)) throw new Error(`bundle source missing: ${rel}`);
    const source = fs.readFileSync(abs, 'utf8').replace(/\s*$/, '');
    // A literal closing tag inside a source file would end the block early.
    if (guard.test(source)) {
      throw new Error(`${rel} contains a literal ${guard.source} and cannot be inlined`);
    }
    return `/* --- ${rel} --- */\n${source}\n`;
  }).join('\n');
}

/**
 * Replaces the contents of one tag, preserving the surrounding markup exactly.
 * `from` selects which occurrence to take, so the <style> in <head> and the
 * <script> at the end of <body> are each found unambiguously.
 */
function replaceBlock(html, openTag, closeTag, body, fromEnd) {
  const open = fromEnd ? html.lastIndexOf(openTag) : html.indexOf(openTag);
  if (open === -1) throw new Error(`index.html has no ${openTag} block`);
  const bodyStart = open + openTag.length;
  const close = html.indexOf(closeTag, bodyStart);
  if (close === -1) throw new Error(`index.html has an unterminated ${openTag} block`);
  return `${html.slice(0, bodyStart)}\n\n${body}\n${html.slice(close)}`;
}

/**
 * Stamps a build id into the page and into api/_buildid.js.
 *
 * Derived from the bundle contents rather than a timestamp, so it is stable:
 * rebuilding unchanged sources produces the same id, which keeps `--check`
 * meaningful and stops every build showing up as a diff.
 *
 * The point of it is diagnosis — comparing the id the browser loaded against
 * the one /api/version reports tells you instantly whether you're looking at
 * a stale deployment or a stale cache.
 */
function stampBuildId(html, css, js) {
  const id = crypto.createHash('sha256').update(css + js).digest('hex').slice(0, 12);

  fs.writeFileSync(
    path.join(__dirname, 'api', '_buildid.js'),
    '// Generated by build.js — do not edit.\n' +
    `module.exports = ${JSON.stringify(id)};\n`
  );

  const meta = `<meta name="aivideo-build" content="${id}">`;
  const stamped = /<meta name="aivideo-build"[^>]*>/.test(html)
    ? html.replace(/<meta name="aivideo-build"[^>]*>/, meta)
    : html.replace(/<head>/i, `<head>\n  ${meta}`);

  return { html: stamped, id };
}

function main() {
  const check = process.argv.includes('--check');
  const html = fs.readFileSync(INDEX, 'utf8');

  const css = buildBundle(CSS_ORDER, /<\/style/i);
  const js = buildBundle(JS_ORDER, /<\/script/i);

  let next = replaceBlock(html, '<style>', '</style>', css, false);
  next = replaceBlock(next, '<script>', '</script>', js, true);
  next = stampBuildId(next, css, js).html;

  if (next === html) {
    console.log('index.html is in sync with styles/ and js/');
    return;
  }

  if (check) {
    console.error('index.html is OUT OF SYNC with styles/ or js/ — run `npm run bundle`.');
    process.exit(1);
  }

  fs.writeFileSync(INDEX, next);
  const kb = (Buffer.byteLength(next) / 1024).toFixed(0);
  console.log(`index.html rebuilt from ${CSS_ORDER.length} stylesheets and ${JS_ORDER.length} scripts (${kb} KB)`);
}

main();
